server:
  port: 8001

spring:
  application:
    name: e

eureka:
  server:
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false