server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: api-user
          uri: lb://api-user
          predicates:
            - Path=/user/**
        - id: api-hospital
          uri: lb://api-hospital
          predicates:
            - Path=/hospital/**
        - id: api-notice
          uri: lb://api-hospital
          predicates:
            - Path=/notice/**
        - id: api-review
          uri: lb://api-hospital
          predicates:
            - Path=/review/**
        - id: api-reservation
          uri: lb://api-reservation
          predicates:
            - Path=/reservation/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user
        url: /user/v3/api-docs
      - name: reservation
        url: /reservation/v3/api-docs