server:
  port: 8081
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    test-connection: true

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    jpa:
      repositories:
        enabled: true
  application:
    name: api-user

springdoc:
  api-docs:
    path: /user/v3/api-docs
  swagger-ui:
    path: /user/swagger-ui.html
