server:
  port: 8081
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  datasource:
    url: jdbc:mariadb://192.0.4.202:3306/one
    username: one
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    jpa:
      repositories:
        enabled: true
  application:
    name: admin


