server:
  port: 8083
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: api-hospital
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /hospital/v3/api-docs
  swagger-ui:
    path: /hospital/swagger-ui.html
